baseURL = "https://5pc.pages.dev/"
theme = "hugo-bearblog"
title = "5PC®"
author = "5PC®"
copyright = "Copyright © 2026, Five Pillars Compendium®"
locale = "en-US"
timeZone = "Asia/Jakarta"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
description = "Film. Series. Books. Games. Music. One title, five pillars."
favicon = "images/favicon.png"
images = ["images/share.png"]
title = "5PC®"
pillars = ["film", "series", "books", "games", "music"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
